server:
  port: 8080
spring:
  application:
    name: "accounts"
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
        ddl-auto: update
    show-sql: true
  #  datasource:
  #    url: jdbc:mysql://localhost:3306/accountsdb
  #    username: root
  #    password: root
  sql:
    init:
      mode:
        always
  config:
    import: "optional:configserver:http://localhost:8071/"
  profiles:
    active:

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "accounts"
    description: "DucAnh Accounts Application"
    version: "1.0.0"

logging:
  level:
    com:
      eazybytes:
        accounts:
          DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 30
        wait-duration-in-open-state: 30000
#resilience4j.retry:
#  configs:
#    default:
#      maxRetryAttempts: 3
#      wait-duration: 500
#      enable-exponential-backoff: true
#      exponential-backoff-multiplier: 2
#      ignore-exceptions:
#        - java.lang.NullPointerException
#      retry-exceptions:
#        - java.util.concurrent.TimeoutException

build:
  version : 2.0

resilience4j.retry:
  configs:
    default:
      maxRetryAttempts: 3
      waitDuration: 500
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      ignoreExceptions:
        - java.lang.NullPointerException
#      retryExceptions:
#        - java.util.concurrent.TimeoutException

resilience4j.ratelimiter:
  configs:
    default:
      timeoutDuration: 1000
      limitRefreshPeriod: 5000
      limitForPeriod: 1