spring:
  application:
    name: "configserver"
  profiles:
#    active: native
    active: git
  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config"
#          search-locations: "file:///D://Learn Microservices//configserver//src//main//resources//config"
        git:
          uri: "https://github.com/ducaanhlehuu/eazybytes-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true


server:
  port: 8071
encrypt:
  key: "123"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

